/**
 * Alert Model / Schema
 * Stores budget and spending alerts generated by the system
 * 
 * Data Structure:
 * - Budget exceeded alerts
 * - High-value transaction alerts
 * - Unusual spending pattern alerts
 */

const mongoose = require('mongoose');

const alertSchema = new mongoose.Schema(
  {
    // Alert Type
    alert_type: {
      type: String,
      enum: [
        'budget_exceeded',      // Monthly spending exceeded budget limit
        'high_transaction',     // Single transaction above threshold
        'unusual_pattern',      // Spending significantly higher than normal
        'category_high',        // Category spending exceeded threshold
      ],
      required: true,
      index: true,
    },

    // Alert Content
    title: {
      type: String,
      required: true,
    },
    message: {
      type: String,
      required: true,
    },
    severity: {
      type: String,
      enum: ['info', 'warning', 'critical'],
      default: 'warning',
    },

    // Related Data
    related_expense_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Expense',
      default: null,
    },

    // Alert Details
    data: {
      // For budget_exceeded alerts
      month: String,                    // YYYY-MM format
      budget_limit: Number,
      actual_spending: Number,
      excess_amount: Number,

      // For high_transaction alerts
      transaction_amount: Number,
      threshold: Number,

      // For unusual_pattern alerts
      average_spending: Number,
      current_spending: Number,
      variance_percentage: Number,

      // For category_high alerts
      category: String,
      category_limit: Number,
      category_spending: Number,
    },

    // Alert Status
    is_read: {
      type: Boolean,
      default: false,
      index: true,
    },
    is_dismissed: {
      type: Boolean,
      default: false,
    },

    // Timestamps
    created_at: {
      type: Date,
      default: Date.now,
      index: true,
    },
    read_at: {
      type: Date,
      default: null,
    },
    dismissed_at: {
      type: Date,
      default: null,
    },

    // TTL Index: Auto-delete alerts after 90 days
    expires_at: {
      type: Date,
      default: () => new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
      index: { expireAfterSeconds: 0 },
    },
  },
  {
    collection: 'alerts',
  }
);

// Indexes for common queries
alertSchema.index({ is_read: 1, created_at: -1 });
alertSchema.index({ alert_type: 1 });
alertSchema.index({ created_at: -1 });

module.exports = mongoose.model('Alert', alertSchema);
